name: SecurePR Scan

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check scan limit
        run: |
          curl -X POST "https://olmznclvpoxbavihmyqi.supabase.co/functions/v1/check-scan-limit" \
          -H "Authorization: Bearer ${{ secrets.SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"user_id": "${{ github.actor }}"}'
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          output: trivy-results.txt

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config=auto --output=semgrep-results.txt

      - name: Generate PR summary
        run: |
          chmod +x .github/summary-generator.sh
          .github/summary-generator.sh

      - name: Post PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: summary.md
